# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: NewGAN HelloWorld Linux

on:
  push:
    branches: [ build-scripts ]
  pull_request:
    branches: [ build-scripts ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        #apt-get update
        sudo apt-get install git python3-dev python3-pip libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkitgtk-3.0-0 gir1.2-webkit-3.0
        #- name: install docker
        #run: |
        #sudo apt-get update
        #sudo apt-get install docker-ce docker-ce-cli containerd.io
    - name: Beeware dependencies
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m pip install --pre beeware
    - name: Build
      run: |
        briefcase create --no-docker
        briefcase build --no-docker
        briefcase package --no-docker
    - name: Save Installer
      uses: actions/upload-artifact@v1
      with:
        name: NewGAN-Manager-Installer
        path: linux/NewGAN_Manager-0.0.2-x86_64.AppImage
